#pragma checksum "D:\Masters\DIS\Review.me\Review_me\Views\Home\Browse.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "462e7d649eb9dc9c5e018a0f709bcc846cc67eff"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Browse), @"mvc.1.0.view", @"/Views/Home/Browse.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 2 "D:\Masters\DIS\Review.me\Review_me\Views\_ViewImports.cshtml"
using Review_me;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\Masters\DIS\Review.me\Review_me\Views\_ViewImports.cshtml"
using Review_me.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"462e7d649eb9dc9c5e018a0f709bcc846cc67eff", @"/Views/Home/Browse.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"1ffaecef6524ab4510bd221da719e01c472d68c6", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Browse : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n<div class=\"hero-bg-1\">\r\n");
#nullable restore
#line 3 "D:\Masters\DIS\Review.me\Review_me\Views\Home\Browse.cshtml"
     foreach (Book b in ViewBag.Books)
    {

#line default
#line hidden
#nullable disable
            WriteLiteral("        <a");
            BeginWriteAttribute("href", " href=\'", 84, "\'", 151, 1);
#nullable restore
#line 5 "D:\Masters\DIS\Review.me\Review_me\Views\Home\Browse.cshtml"
WriteAttributeValue("", 91, Url.Action("UltimateBook","Home", new { bookId = b.bookId}), 91, 60, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">\r\n        <section class=\"top\">\r\n            <div class=\"form-container1\">\r\n                <img class=\"Book-picture\"");
            BeginWriteAttribute("src", " src=", 270, "", 288, 1);
#nullable restore
#line 8 "D:\Masters\DIS\Review.me\Review_me\Views\Home\Browse.cshtml"
WriteAttributeValue("", 275, b.book_image, 275, 13, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" alt=\"Book\">\r\n                <h4>");
#nullable restore
#line 9 "D:\Masters\DIS\Review.me\Review_me\Views\Home\Browse.cshtml"
               Write(b.title);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h4>\r\n            </div>\r\n        </section>\r\n        </a>\r\n");
#nullable restore
#line 13 "D:\Masters\DIS\Review.me\Review_me\Views\Home\Browse.cshtml"
    }

#line default
#line hidden
#nullable disable
            WriteLiteral("</div>");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
