#pragma checksum "D:\Masters\DIS\Review.me\Review_me\Views\Home\UpdateReview.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "e8895ad50627cd7450d1556989ceb0694879b707"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_UpdateReview), @"mvc.1.0.view", @"/Views/Home/UpdateReview.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 2 "D:\Masters\DIS\Review.me\Review_me\Views\_ViewImports.cshtml"
using Review_me;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "D:\Masters\DIS\Review.me\Review_me\Views\_ViewImports.cshtml"
using Review_me.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"e8895ad50627cd7450d1556989ceb0694879b707", @"/Views/Home/UpdateReview.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"1ffaecef6524ab4510bd221da719e01c472d68c6", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_UpdateReview : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("rel", new global::Microsoft.AspNetCore.Html.HtmlString("stylesheet"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("href", new global::Microsoft.AspNetCore.Html.HtmlString("~/css/site.css"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("action", new global::Microsoft.AspNetCore.Html.HtmlString(""), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("col-lg-7 col-md-7 col-sm-6"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral(@"<meta name=""viewport"" content=""width=device-width, initial-scale=1"">
<script src=""https://code.jquery.com/jquery-1.10.2.min.js""></script>
<link href=""https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"" rel=""stylesheet"">
<script src=""https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.bundle.min.js""></script>
<link rel=""stylesheet"" href=""https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Open+Sans"">
<link rel=""stylesheet"" href=""https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"">
<link rel=""stylesheet"" href=""https://fonts.googleapis.com/icon?family=Material+Icons"">
<link rel=""stylesheet"" href=""https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"">
<script src=""https://code.jquery.com/jquery-3.5.1.min.js""></script>
<script src=""https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js""></script>
<script src=""https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js""></script>

<link href=""ht");
            WriteLiteral("tps://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("link", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "e8895ad50627cd7450d1556989ceb0694879b7075939", async() => {
            }
            );
            __Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.Razor.TagHelpers.UrlResolutionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_Razor_TagHelpers_UrlResolutionTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n\r\n<div class=\"hero-bg\">\r\n    <div class=\"container\">\r\n        <div class=\"card\">\r\n            <div class=\"card-body\">\r\n                <h3 class=\"card-title\"><b>");
#nullable restore
#line 20 "D:\Masters\DIS\Review.me\Review_me\Views\Home\UpdateReview.cshtml"
                                     Write(ViewBag.book.title);

#line default
#line hidden
#nullable disable
            WriteLiteral("</b></h3>\r\n                <h6 class=\"card-subtitle\">by ");
#nullable restore
#line 21 "D:\Masters\DIS\Review.me\Review_me\Views\Home\UpdateReview.cshtml"
                                        Write(ViewBag.book.author);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h6>\r\n                <div class=\"row\">\r\n                    <div class=\"col-lg-5 col-md-5 col-sm-6\">\r\n                        <div class=\"white-box text-center\">\r\n                            <img");
            BeginWriteAttribute("src", " src=", 1618, "", 1647, 1);
#nullable restore
#line 25 "D:\Masters\DIS\Review.me\Review_me\Views\Home\UpdateReview.cshtml"
WriteAttributeValue("", 1623, ViewBag.book.book_image, 1623, 24, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral("\r\n                                 class=\"img-responsive\">\r\n                        </div>\r\n                    </div>\r\n");
#nullable restore
#line 29 "D:\Masters\DIS\Review.me\Review_me\Views\Home\UpdateReview.cshtml"
                     using (Html.BeginForm("UpdateReview", "Home", FormMethod.Post, new { @style = "width: 55%" }))
                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                        ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "e8895ad50627cd7450d1556989ceb0694879b7078823", async() => {
                WriteLiteral("\r\n                            <div class=\"col-lg-7 col-md-7 col-sm-6\">\r\n\r\n                                <label for=\"reviewName\">Enter the review source name:</label>\r\n                                <input type=\"text\" name=\"name\" id=\"name\"");
                BeginWriteAttribute("value", " value=\"", 2223, "\"", 2251, 1);
#nullable restore
#line 35 "D:\Masters\DIS\Review.me\Review_me\Views\Home\UpdateReview.cshtml"
WriteAttributeValue("", 2231, ViewBag.review.name, 2231, 20, false);

#line default
#line hidden
#nullable disable
                EndWriteAttribute();
                WriteLiteral(">\r\n                                <p>Example: \"Sunday Review\"</p>\r\n\r\n                                <label for=\"reviewURL\">Enter the review source URL:</label>\r\n                                <input type=\"text\" name=\"url\" id=\"url\"");
                BeginWriteAttribute("value", " value=", 2485, "", 2511, 1);
#nullable restore
#line 39 "D:\Masters\DIS\Review.me\Review_me\Views\Home\UpdateReview.cshtml"
WriteAttributeValue("", 2492, ViewBag.review.url, 2492, 19, false);

#line default
#line hidden
#nullable disable
                EndWriteAttribute();
                WriteLiteral(">\r\n                                <p>Example: \"http://www.sundayreview.com/xyz\"</p>\r\n\r\n                                <input type=\"hidden\" name=\"bookId\" id=\"bookId\"");
                BeginWriteAttribute("value", " value=", 2677, "", 2706, 1);
#nullable restore
#line 42 "D:\Masters\DIS\Review.me\Review_me\Views\Home\UpdateReview.cshtml"
WriteAttributeValue("", 2684, ViewBag.review.bookId, 2684, 22, false);

#line default
#line hidden
#nullable disable
                EndWriteAttribute();
                BeginWriteAttribute("style", " style=\"", 2706, "\"", 2714, 0);
                EndWriteAttribute();
                WriteLiteral(">\r\n\r\n                                <input type=\"hidden\" name=\"reviewLinkId\" id=\"reviewLinkId\"");
                BeginWriteAttribute("value", " value=", 2810, "", 2845, 1);
#nullable restore
#line 44 "D:\Masters\DIS\Review.me\Review_me\Views\Home\UpdateReview.cshtml"
WriteAttributeValue("", 2817, ViewBag.review.reviewLinkId, 2817, 28, false);

#line default
#line hidden
#nullable disable
                EndWriteAttribute();
                BeginWriteAttribute("style", " style=\"", 2845, "\"", 2853, 0);
                EndWriteAttribute();
                WriteLiteral(">\r\n\r\n                                <input type=\"submit\" value=\"Save\" id=\"cta-btn\">\r\n                            </div>\r\n                        ");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n");
#nullable restore
#line 49 "D:\Masters\DIS\Review.me\Review_me\Views\Home\UpdateReview.cshtml"
                    }

#line default
#line hidden
#nullable disable
            WriteLiteral("                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; }
    }
}
#pragma warning restore 1591
